---
title: "第2章"
author: "早見　均"
format: docx
editor: visual
---

## Running Code

```{r}
#| echo: false
Kanji="MS Gothic"
RInfor=sessionInfo()$running
if( length(grep("mac",RInfor))>0 ) {
#  Kanji="YuMincho"
  Kanji="HiraKakuProN-W3"
}
par(family=Kanji)

# "HiraKakuProN-W3"
# ”HiraMinProN-W3″
# ”HiraMinProN-W6″
# ”HiraKakuProN-W6″
# ggplot2の時
# theme_bw(base_family = "HiraKakuProN-W3")
```

```{r}
#| echo: true
#| fig-width: 3
#| fig-height: 3
#| fig-cap: "Uniform Random Variable"
#| fig-cap-location: "bottom"

n=1000
set.seed(563)
x=runif(n)
y=runif(n)
theta=seq(0,pi/2,0.01)
# plot(x,y,xlim=c(0,1),ylim=c(0,1),cex=0.01,sub="円周率の計算")
plot(x,y,xlim=c(0,1),ylim=c(0,1),cex=0.01)
lines(cos(theta),sin(theta),col="black",lty=1,lwd=3)
# curve(sqrt(1-x**2),from=0,to=1,col="red",add=TRUE)
```

```{python}
import matplotlib.pyplot as plt
import numpy as np
x=np.linspace(0.01,10,100)
fig=plt.figure()
plt.plot(x,np.sin(x)*x,'-')
plt.plot(x,np.cos(x)*x,'--')
plt.show()
```

```{r}
# 発生させる確率変数の個数
n=500000
set.seed(563)
x=runif(n)
y=runif(n)
r2=x**2+y**2
# r=length(which(r2<1))/n
r=sum(ifelse(r2<=1,1,0))/n
print(r*4)
```

```{r}
n=10000000
set.seed(563)
x=runif(n)
y=runif(n)
r2=x**2+y**2
z=ifelse(r2<=1,1,0)
mypi=cumsum(ifelse(r2<=1,1,0))/seq(1,n)*4
xlabel=paste("πの推定値=",toString(mypi[n],width=12))
ylabel="πの推定値"
id=seq(10000,n,by=10000)
plot(mypi[id],type="l",ylim=c(3.135,3.15),xlab=xlabel,ylab=ylabel,sub="円周率の収束",family=Kanji)
abline(h=pi,col="red")

xlabel=paste("Estimated pi=",toString(mypi[n],width=12))
ylabel="Estimated pi"
id=seq(10000,n,by=10000)
plot(mypi[id],type="l",ylim=c(3.135,3.15),xlab=xlabel,ylab=ylabel)
abline(h=pi,col=1,lty=3,lwd=2)

par(family=Kanji)
plot(mypi[id],type="l",ylim=c(3.1385,3.14468),xlab=xlabel,ylab=ylabel)
abline(h=pi,col=1,lty=3,lwd=2)
legend("bottomright","万回",cex=0.8,bty="n")
```

```{r coded_by_ChatGPT_20240323}
# Function to estimate pi using Monte Carlo simulation
estimate_pi <- function(num_points) {
  inside_circle <- 0
  
  for (i in 1:num_points) {
    x <- runif(1, min = -1, max = 1)
    y <- runif(1, min = -1, max = 1)
    if (x^2 + y^2 <= 1) {
      inside_circle <- inside_circle + 1
    }
  }
  
  # Estimate pi
  estimated_pi <- 4 * inside_circle / num_points
  
  return(estimated_pi)
}

# Number of points to generate
num_points <- 100000

# Estimate pi
estimated_pi <- estimate_pi(num_points)

cat("Estimated value of pi:", estimated_pi, "\n")
```

```{r}
# 消費者物価指数 csv, shift-jis
url="https://www.e-stat.go.jp/stat-search/file-download?statInfId=000032103844&fileKind=1"
filename_csv="cpi.csv"
download.file(url, filename_csv, method = "auto")
cpi=read.csv(filename_csv,fileEncoding = "shift-jis")
cpi=cpi[-c(1:5),]
rownames(cpi)=NULL
colnames(cpi)[1]="年月"
m=dim(cpi)[2]
cpi[,2:m]=apply(cpi[,2:m],2,as.numeric)
n=length(cpi[,1]) ; last_month=cpi[n,1]
dlnCPI=diff(log(cpi$総合),lag=12)*100
last_year=as.integer(as.numeric(last_month)/100)
last_month=as.numeric(last_month)/100-last_year
last_cpi=last_year+(last_month-0.01)/0.12
start_cpi=1971.0
Month_cpi=seq(start_cpi,last_cpi,by=1/12)
# plot(Month_cpi,dlnCPI,type="l",xlab="年",ylab="%",sub="総合CPI変化率(対前年比)",family=Kanji)

pdf(file="fig0205.pdf",family="Japan1HeiMin")
plot(Month_cpi,dlnCPI,type="l",xlab="年",ylab="%")
abline(h=0,lty="dotted")

dev.off()

# SNA

url="https://www.esri.cao.go.jp/jp/sna/data/data_list/sokuhou/files/2025/qe252/tables/gaku-mg2521.csv"
sna=read.csv(url,fileEncoding="shift-jis")

library(readxl)
# 国勢調査令和2年 xlsx 単一シート
url="https://www.e-stat.go.jp/stat-search/file-download?statInfId=000032142402&fileKind=0"
filename_xlsx="pop_census.xlsx"
download.file(url, filename_xlsx, method = "auto")

pop_column_names <- c("code","Pref2000","RCode2000","R2000","Pref2020","RCode2020","RName","total","male","female","total2015","dN","r_dN","r_gender","area_km2","density","HH","HH_generic","HH_facility","HH2015","dHH","r_dHH","HHmem","HHmem_g","HHmem_f")
pop=read_xlsx(filename_xlsx,col_names =pop_column_names)
file.remove(filename_xlsx)

pop=pop[-c(1:14),]
rownames(pop)=NULL
# m=dim(pop)[2]
# pop=apply(pop,2,na.omit)
# pop[,8:m]=apply(pop[,8:m],2,as.numeric)

# 労働力調査 長期時系列 シートが複数ある
url="https://www.e-stat.go.jp/stat-search/file-download?statInfId=000031831358&fileKind=0"
filename_xlsx="lfs.xlsx"
download.file(url, filename_xlsx, method = "auto")

lfs_colnames=c("Year","Month","Month_en","Blnk","LF","LF_m","LF_f","Emp","Emp_m","Emp_f","Empee","Empee_m","Empee_f","U","U_m","U_f","NLF","NLF_m","NLF_f","UR","UR_m","UR_f")

lfs=read_xlsx(filename_xlsx,sheet="原数値",col_names = lfs_colnames)
start_year_lfs=na.omit(as.numeric(lfs$Year[1:20]))[1]
id_start=which(lfs$Year[1:20]=="※注_Notes")
n=dim(lfs)[1]
last_year_lfs=na.omit(as.numeric(lfs$Year[(n-20):n]))[1]
idx_last=which(is.na(lfs$LF))
idx=which(idx_last>id_start)[1]
id_last=idx_last[idx]-1
lfs_data=lfs[id_start:id_last,]
start_month_lfs=as.numeric(gsub("月","",lfs$Month[id_start]))
last_month_lfs=as.numeric(gsub("月","",lfs$Month[id_last]))
start_month_lfs=as.numeric(start_month_lfs)/100
last_month_lfs=as.numeric(last_month_lfs)/100
start_lfs=start_year_lfs+(start_month_lfs-0.01)/0.12
last_lfs=last_year_lfs+(last_month_lfs-0.01)/0.12
Month_lfs=seq(start_lfs,last_lfs,by=1/12)

plot(Month_lfs,lfs_data$UR,type="l",sub="",ylab="%",xlab="完全失業率",family=Kanji)

d_last=(last_cpi-last_lfs)*12
d_first=(start_cpi-start_lfs)*12
if(d_first<0){ d_cpi=-d_first+1; d_lfs=1 }
if(d_first>0){ d_lfs=d_first+1; d_cpi=1 }
if(d_last<0){ e_lfs=d_last ; e_cpi=0 }
if(d_last>0){ e_cpi=-d_last; e_lfs=0 }
n_cpi=length(dlnCPI)
UR=as.numeric(lfs_data$U)/as.numeric(lfs_data$LF)*100
n_lfs=length(UR)

pdf(file="fig0206.pdf",family="Japan1HeiMin")
plot(UR[d_lfs:(n_lfs+e_lfs)],dlnCPI[d_cpi:(n_cpi+e_cpi)],cex=0.2,xlab="完全失業率",ylab="インフレ率 (CPI)")
dev.off()
```

```{r}
dlnCPI=ts(dlnCPI,start=c(1971,1),frequency=12)
plot.ts(dlnCPI,type="l",family=Kanji)
abline(h=0,lty="dotted")
```
